# Site settings
title: BrightBikes - Light Up Your Community!
description: Build and join a fleet of art bikes created by Central Florida makers!

# this means to ignore newlines until "baseurl:"
#baseurl: "/brightbikes.org" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2021 - Start Bootstrap
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
